In [1]:
# Random Vector Tasks

import numpy as np

# 1. Create random vector of integers from 1 to 20
arr = np.random.randint(1, 21, size=15)
print("Original array:\n", arr)

# 2. Reshape to 3 by 5
reshaped_arr = arr.reshape(3, 5)
print("\nReshaped (3x5) array:\n", reshaped_arr)

# 3. Print shape
print("\nShape of reshaped array:", reshaped_arr.shape)

# 4. Replace max in each row with 0
for i in range(reshaped_arr.shape[0]):
    max_index = reshaped_arr[i].argmax()
    reshaped_arr[i][max_index] = 0
print("\nArray after replacing max in each row with 0:\n", reshaped_arr)


Original array:
 [19  9 11  3 16 14  9 15 18 12  9 17 16 11 18]

Reshaped (3x5) array:
 [[19  9 11  3 16]
 [14  9 15 18 12]
 [ 9 17 16 11 18]]

Shape of reshaped array: (3, 5)

Array after replacing max in each row with 0:
 [[ 0  9 11  3 16]
 [14  9 15  0 12]
 [ 9 17 16 11  0]]


In [2]:
# 2D Array with 4-byte Integers

array_4x3 = np.zeros((4, 3), dtype=np.int32)
print("\n2D array (4x3) with 4-byte integers:\n", array_4x3)
print("Shape:", array_4x3.shape)
print("Type:", type(array_4x3))
print("Data type:", array_4x3.dtype)



2D array (4x3) with 4-byte integers:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [3]:
# Eigenvalues and Eigenvectors

A = np.array([[3, -2],
              [1,  0]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:\n", eigenvalues)
print("Right Eigenvectors:\n", eigenvectors)



Eigenvalues:
 [2. 1.]
Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
# Sum of Diagonal Elements

B = np.array([[0, 1, 2],
              [3, 4, 5]])
diagonal_sum = np.trace(B)
print("\nSum of diagonal elements:", diagonal_sum)



Sum of diagonal elements: 4


In [5]:
# Reshape Without Changing Data

original_array = np.array([[1, 2],
                           [3, 4],
                           [5, 6]])
reshaped_array = original_array.reshape(2, 3)
print("\nOriginal array (3x2):\n", original_array)
print("Reshaped array (2x3):\n", reshaped_array)



Original array (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]
